//! Data-driven configuration and channel editors.
//!
//! Rather than hand-writing a message variant per protobuf field, each
//! config section is described by a [`SectionSpec`]: a list of [`Field`]s
//! with a key, label, help text and a [`FieldKind`]. Reading and writing the
//! underlying protobuf is generated by a small macro, so adding a field is a
//! one-line change and the UI renders every section with the same widgets.

use std::collections::HashMap;

use meshtastic_protobufs::meshtastic::config::{
    BluetoothConfig, DeviceConfig, DisplayConfig, LoRaConfig, NetworkConfig, PositionConfig,
    PowerConfig, SecurityConfig,
};
use meshtastic_protobufs::meshtastic::module_config::{
    CannedMessageConfig, ExternalNotificationConfig, MqttConfig, RangeTestConfig, SerialConfig,
    StoreForwardConfig, TelemetryConfig,
};
use meshtastic_protobufs::meshtastic::{
    Channel, ChannelSettings, Config, ModuleConfig, config, module_config,
};

// Enum option tables (label, value)

pub const REGIONS: &[(&str, i32)] = &[
    ("Unset", 0),
    ("US", 1),
    ("EU 433", 2),
    ("EU 868", 3),
    ("CN", 4),
    ("JP", 5),
    ("ANZ", 6),
    ("KR", 7),
    ("TW", 8),
    ("RU", 9),
    ("IN", 10),
    ("NZ 865", 11),
    ("TH", 12),
    ("2.4 GHz", 13),
    ("UA 433", 14),
    ("UA 868", 15),
    ("MY 433", 16),
    ("MY 919", 17),
    ("SG 923", 18),
    ("PH 433", 19),
    ("PH 868", 20),
    ("PH 915", 21),
    ("ANZ 433", 22),
];

pub const MODEM_PRESETS: &[(&str, i32)] = &[
    ("Long Fast", 0),
    ("Long Slow", 1),
    ("Very Long Slow", 2),
    ("Medium Slow", 3),
    ("Medium Fast", 4),
    ("Short Slow", 5),
    ("Short Fast", 6),
    ("Long Moderate", 7),
    ("Short Turbo", 8),
];

pub const ROLES: &[(&str, i32)] = &[
    ("Client", 0),
    ("Client Mute", 1),
    ("Router", 2),
    ("Router + Client", 3),
    ("Repeater", 4),
    ("Tracker", 5),
    ("Sensor", 6),
    ("TAK", 7),
    ("Client Hidden", 8),
    ("Lost & Found", 9),
    ("TAK Tracker", 10),
    ("Router Late", 11),
];

pub const REBROADCAST_MODES: &[(&str, i32)] = &[
    ("All", 0),
    ("All (skip decoding)", 1),
    ("Local only", 2),
    ("Known only", 3),
    ("None", 4),
    ("Core port numbers only", 5),
];

pub const GPS_MODES: &[(&str, i32)] = &[("Disabled", 0), ("Enabled", 1), ("Not present", 2)];

pub const DISPLAY_MODES: &[(&str, i32)] = &[
    ("Default", 0),
    ("Two colour", 1),
    ("Inverted", 2),
    ("Colour", 3),
];

pub const UNITS: &[(&str, i32)] = &[("Metric", 0), ("Imperial", 1)];

pub const GPS_FORMATS: &[(&str, i32)] = &[("Decimal", 0), ("DMS", 1), ("UTM", 2)];

pub const OLED_TYPES: &[(&str, i32)] = &[
    ("Auto", 0),
    ("SSD1306", 1),
    ("SH1106", 2),
    ("SH1107", 3),
    ("SH1107 128x64", 4),
];

pub const SERIAL_MODES: &[(&str, i32)] = &[
    ("Default", 0),
    ("Simple", 1),
    ("Protobuf", 2),
    ("Text message", 3),
    ("NMEA", 4),
    ("CalTopo", 5),
    ("WS85", 6),
    ("VeDirect", 7),
];

pub const PAIRING_MODES: &[(&str, i32)] = &[("Random PIN", 0), ("Fixed PIN", 1), ("No PIN", 2)];

pub const ADDRESS_MODES: &[(&str, i32)] = &[("DHCP", 0), ("Static", 1)];

pub const CHANNEL_ROLES: &[(&str, i32)] = &[("Disabled", 0), ("Primary", 1), ("Secondary", 2)];

// Field model

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Section {
    Lora,
    Device,
    Position,
    Power,
    Network,
    Display,
    Bluetooth,
    Security,
    Mqtt,
    Serial,
    Telemetry,
    CannedMessage,
    ExternalNotification,
    StoreForward,
    RangeTest,
}

impl Section {
    /// Whether this section belongs to the module config family.
    pub fn is_module(self) -> bool {
        matches!(
            self,
            Section::Mqtt
                | Section::Serial
                | Section::Telemetry
                | Section::CannedMessage
                | Section::ExternalNotification
                | Section::StoreForward
                | Section::RangeTest
        )
    }
}

#[derive(Debug, Clone, Copy)]
pub enum FieldKind {
    Bool,
    U32 {
        min: u32,
        max: u32,
    },
    I32 {
        min: i32,
        max: i32,
    },
    F32,
    Text,
    Password,
    /// A choice among `(label, value)` pairs.
    Enum(&'static [(&'static str, i32)]),
}

#[derive(Debug, Clone, Copy)]
pub struct Field {
    pub key: &'static str,
    pub label: &'static str,
    pub help: &'static str,
    pub kind: FieldKind,
}

#[derive(Debug, Clone, Copy)]
pub struct SectionSpec {
    pub section: Section,
    pub title: &'static str,
    pub description: &'static str,
    pub fields: &'static [Field],
}

const fn text(key: &'static str, label: &'static str, help: &'static str) -> Field {
    Field {
        key,
        label,
        help,
        kind: FieldKind::Text,
    }
}
const fn password(key: &'static str, label: &'static str, help: &'static str) -> Field {
    Field {
        key,
        label,
        help,
        kind: FieldKind::Password,
    }
}
const fn boolean(key: &'static str, label: &'static str, help: &'static str) -> Field {
    Field {
        key,
        label,
        help,
        kind: FieldKind::Bool,
    }
}
const fn u32f(
    key: &'static str,
    label: &'static str,
    help: &'static str,
    min: u32,
    max: u32,
) -> Field {
    Field {
        key,
        label,
        help,
        kind: FieldKind::U32 { min, max },
    }
}
const fn i32f(
    key: &'static str,
    label: &'static str,
    help: &'static str,
    min: i32,
    max: i32,
) -> Field {
    Field {
        key,
        label,
        help,
        kind: FieldKind::I32 { min, max },
    }
}
const fn f32f(key: &'static str, label: &'static str, help: &'static str) -> Field {
    Field {
        key,
        label,
        help,
        kind: FieldKind::F32,
    }
}
const fn enumerate(
    key: &'static str,
    label: &'static str,
    help: &'static str,
    options: &'static [(&'static str, i32)],
) -> Field {
    Field {
        key,
        label,
        help,
        kind: FieldKind::Enum(options),
    }
}

// Generated read/write per config type

macro_rules! io_read {
    ($v:expr, text) => {
        $v.clone()
    };
    ($v:expr, $kind:ident) => {
        $v.to_string()
    };
}

macro_rules! io_parse {
    ($v:expr, text) => {
        Ok::<_, String>($v.to_string())
    };
    ($v:expr, bool) => {
        Ok::<_, String>($v.eq_ignore_ascii_case("true"))
    };
    ($v:expr, u32) => {
        $v.trim().parse::<u32>().map_err(|e| e.to_string())
    };
    ($v:expr, i32) => {
        $v.trim().parse::<i32>().map_err(|e| e.to_string())
    };
    ($v:expr, f32) => {
        $v.trim().parse::<f32>().map_err(|e| e.to_string())
    };
}

macro_rules! config_io {
    ($read:ident, $write:ident, $ty:ty, { $( $key:literal => $field:ident : $kind:ident ),* $(,)? }) => {
        fn $read(c: &$ty, key: &str) -> String {
            match key {
                $( $key => io_read!(c.$field, $kind), )*
                _ => String::new(),
            }
        }
        fn $write(c: &mut $ty, key: &str, value: &str) -> Result<(), String> {
            match key {
                $( $key => {
                    c.$field = io_parse!(value, $kind)?;
                    Ok(())
                } )*
                _ => Err(format!("unknown field: {key}")),
            }
        }
    };
}

config_io!(read_lora, write_lora, LoRaConfig, {
    "region" => region : i32,
    "use_preset" => use_preset : bool,
    "modem_preset" => modem_preset : i32,
    "hop_limit" => hop_limit : u32,
    "tx_enabled" => tx_enabled : bool,
    "tx_power" => tx_power : i32,
    "channel_num" => channel_num : u32,
    "frequency_offset" => frequency_offset : f32,
    "override_duty_cycle" => override_duty_cycle : bool,
    "ignore_mqtt" => ignore_mqtt : bool,
    "config_ok_to_mqtt" => config_ok_to_mqtt : bool,
});

config_io!(read_device, write_device, DeviceConfig, {
    "role" => role : i32,
    "rebroadcast_mode" => rebroadcast_mode : i32,
    "node_info_broadcast_secs" => node_info_broadcast_secs : u32,
    "disable_triple_click" => disable_triple_click : bool,
    "led_heartbeat_disabled" => led_heartbeat_disabled : bool,
    "tzdef" => tzdef : text,
});

config_io!(read_position, write_position, PositionConfig, {
    "position_broadcast_secs" => position_broadcast_secs : u32,
    "position_broadcast_smart_enabled" => position_broadcast_smart_enabled : bool,
    "fixed_position" => fixed_position : bool,
    "gps_mode" => gps_mode : i32,
    "gps_update_interval" => gps_update_interval : u32,
    "broadcast_smart_minimum_distance" => broadcast_smart_minimum_distance : u32,
});

config_io!(read_power, write_power, PowerConfig, {
    "is_power_saving" => is_power_saving : bool,
    "on_battery_shutdown_after_secs" => on_battery_shutdown_after_secs : u32,
    "wait_bluetooth_secs" => wait_bluetooth_secs : u32,
    "sds_secs" => sds_secs : u32,
    "ls_secs" => ls_secs : u32,
    "min_wake_secs" => min_wake_secs : u32,
});

config_io!(read_network, write_network, NetworkConfig, {
    "wifi_enabled" => wifi_enabled : bool,
    "wifi_ssid" => wifi_ssid : text,
    "wifi_psk" => wifi_psk : text,
    "eth_enabled" => eth_enabled : bool,
    "ntp_server" => ntp_server : text,
    "address_mode" => address_mode : i32,
});

config_io!(read_display, write_display, DisplayConfig, {
    "screen_on_secs" => screen_on_secs : u32,
    "auto_screen_carousel_secs" => auto_screen_carousel_secs : u32,
    "displaymode" => displaymode : i32,
    "units" => units : i32,
    "gps_format" => gps_format : i32,
    "oled" => oled : i32,
    "flip_screen" => flip_screen : bool,
    "compass_north_top" => compass_north_top : bool,
});

config_io!(read_bluetooth, write_bluetooth, BluetoothConfig, {
    "enabled" => enabled : bool,
    "mode" => mode : i32,
    "fixed_pin" => fixed_pin : u32,
});

config_io!(read_security, write_security, SecurityConfig, {
    "is_managed" => is_managed : bool,
    "serial_enabled" => serial_enabled : bool,
    "debug_log_api_enabled" => debug_log_api_enabled : bool,
    "admin_channel_enabled" => admin_channel_enabled : bool,
});

config_io!(read_mqtt, write_mqtt, MqttConfig, {
    "enabled" => enabled : bool,
    "address" => address : text,
    "username" => username : text,
    "password" => password : text,
    "encryption_enabled" => encryption_enabled : bool,
    "json_enabled" => json_enabled : bool,
    "tls_enabled" => tls_enabled : bool,
    "root" => root : text,
    "proxy_to_client_enabled" => proxy_to_client_enabled : bool,
    "map_reporting_enabled" => map_reporting_enabled : bool,
});

config_io!(read_serial, write_serial, SerialConfig, {
    "enabled" => enabled : bool,
    "echo" => echo : bool,
    "rxd" => rxd : u32,
    "txd" => txd : u32,
    "baud" => baud : i32,
    "timeout" => timeout : u32,
    "mode" => mode : i32,
    "override_console_serial_port" => override_console_serial_port : bool,
});

config_io!(read_telemetry, write_telemetry, TelemetryConfig, {
    "device_update_interval" => device_update_interval : u32,
    "environment_update_interval" => environment_update_interval : u32,
    "environment_measurement_enabled" => environment_measurement_enabled : bool,
    "environment_screen_enabled" => environment_screen_enabled : bool,
    "environment_display_fahrenheit" => environment_display_fahrenheit : bool,
    "air_quality_enabled" => air_quality_enabled : bool,
    "air_quality_interval" => air_quality_interval : u32,
    "power_measurement_enabled" => power_measurement_enabled : bool,
    "power_update_interval" => power_update_interval : u32,
    "health_measurement_enabled" => health_measurement_enabled : bool,
    "health_update_interval" => health_update_interval : u32,
});

config_io!(read_canned, write_canned, CannedMessageConfig, {
    "enabled" => enabled : bool,
    "allow_input_source" => allow_input_source : text,
    "send_bell" => send_bell : bool,
});

config_io!(read_extnotif, write_extnotif, ExternalNotificationConfig, {
    "enabled" => enabled : bool,
    "output_ms" => output_ms : u32,
    "active" => active : bool,
    "alert_message" => alert_message : bool,
    "alert_bell" => alert_bell : bool,
    "use_pwm" => use_pwm : bool,
    "nag_timeout" => nag_timeout : u32,
});

config_io!(read_storeforward, write_storeforward, StoreForwardConfig, {
    "enabled" => enabled : bool,
    "heartbeat" => heartbeat : bool,
    "records" => records : u32,
    "history_return_max" => history_return_max : u32,
    "history_return_window" => history_return_window : u32,
    "is_server" => is_server : bool,
});

config_io!(read_rangetest, write_rangetest, RangeTestConfig, {
    "enabled" => enabled : bool,
    "sender" => sender : u32,
    "save" => save : bool,
});

// SectionValue: one concrete config behind a common enum

#[derive(Debug, Clone)]
pub enum SectionValue {
    Device(DeviceConfig),
    Position(PositionConfig),
    Power(PowerConfig),
    Network(NetworkConfig),
    Display(DisplayConfig),
    Lora(LoRaConfig),
    Bluetooth(BluetoothConfig),
    Security(SecurityConfig),
    Mqtt(MqttConfig),
    Serial(SerialConfig),
    Telemetry(TelemetryConfig),
    CannedMessage(CannedMessageConfig),
    ExternalNotification(ExternalNotificationConfig),
    StoreForward(StoreForwardConfig),
    RangeTest(RangeTestConfig),
}

impl SectionValue {
    pub fn default_for(section: Section) -> Self {
        match section {
            Section::Device => SectionValue::Device(DeviceConfig::default()),
            Section::Position => SectionValue::Position(PositionConfig::default()),
            Section::Power => SectionValue::Power(PowerConfig::default()),
            Section::Network => SectionValue::Network(NetworkConfig::default()),
            Section::Display => SectionValue::Display(DisplayConfig::default()),
            Section::Lora => SectionValue::Lora(LoRaConfig::default()),
            Section::Bluetooth => SectionValue::Bluetooth(BluetoothConfig::default()),
            Section::Security => SectionValue::Security(SecurityConfig::default()),
            Section::Mqtt => SectionValue::Mqtt(MqttConfig::default()),
            Section::Serial => SectionValue::Serial(SerialConfig::default()),
            Section::Telemetry => SectionValue::Telemetry(TelemetryConfig::default()),
            Section::CannedMessage => SectionValue::CannedMessage(CannedMessageConfig::default()),
            Section::ExternalNotification => {
                SectionValue::ExternalNotification(ExternalNotificationConfig::default())
            }
            Section::StoreForward => SectionValue::StoreForward(StoreForwardConfig::default()),
            Section::RangeTest => SectionValue::RangeTest(RangeTestConfig::default()),
        }
    }

    /// Extract the relevant section from a downloaded `Config`.
    pub fn from_config(section: Section, config: &Config) -> Option<Self> {
        Some(match (section, config.payload_variant.as_ref()?) {
            (Section::Device, config::PayloadVariant::Device(c)) => SectionValue::Device(c.clone()),
            (Section::Position, config::PayloadVariant::Position(c)) => SectionValue::Position(*c),
            (Section::Power, config::PayloadVariant::Power(c)) => SectionValue::Power(*c),
            (Section::Network, config::PayloadVariant::Network(c)) => {
                SectionValue::Network(c.clone())
            }
            (Section::Display, config::PayloadVariant::Display(c)) => SectionValue::Display(*c),
            (Section::Lora, config::PayloadVariant::Lora(c)) => SectionValue::Lora(c.clone()),
            (Section::Bluetooth, config::PayloadVariant::Bluetooth(c)) => {
                SectionValue::Bluetooth(*c)
            }
            (Section::Security, config::PayloadVariant::Security(c)) => {
                SectionValue::Security(c.clone())
            }
            _ => return None,
        })
    }

    /// Extract the relevant section from a downloaded `ModuleConfig`.
    pub fn from_module_config(section: Section, config: &ModuleConfig) -> Option<Self> {
        Some(match (section, config.payload_variant.as_ref()?) {
            (Section::Mqtt, module_config::PayloadVariant::Mqtt(c)) => {
                SectionValue::Mqtt(c.clone())
            }
            (Section::Serial, module_config::PayloadVariant::Serial(c)) => SectionValue::Serial(*c),
            (Section::Telemetry, module_config::PayloadVariant::Telemetry(c)) => {
                SectionValue::Telemetry(*c)
            }
            (Section::CannedMessage, module_config::PayloadVariant::CannedMessage(c)) => {
                SectionValue::CannedMessage(c.clone())
            }
            (
                Section::ExternalNotification,
                module_config::PayloadVariant::ExternalNotification(c),
            ) => SectionValue::ExternalNotification(*c),
            (Section::StoreForward, module_config::PayloadVariant::StoreForward(c)) => {
                SectionValue::StoreForward(*c)
            }
            (Section::RangeTest, module_config::PayloadVariant::RangeTest(c)) => {
                SectionValue::RangeTest(*c)
            }
            _ => return None,
        })
    }

    /// Wrap as a `Config` (device sections only).
    pub fn to_config(&self) -> Option<Config> {
        let payload_variant = match self {
            SectionValue::Device(c) => config::PayloadVariant::Device(c.clone()),
            SectionValue::Position(c) => config::PayloadVariant::Position(*c),
            SectionValue::Power(c) => config::PayloadVariant::Power(*c),
            SectionValue::Network(c) => config::PayloadVariant::Network(c.clone()),
            SectionValue::Display(c) => config::PayloadVariant::Display(*c),
            SectionValue::Lora(c) => config::PayloadVariant::Lora(c.clone()),
            SectionValue::Bluetooth(c) => config::PayloadVariant::Bluetooth(*c),
            SectionValue::Security(c) => config::PayloadVariant::Security(c.clone()),
            _ => return None,
        };
        Some(Config {
            payload_variant: Some(payload_variant),
        })
    }

    /// Wrap as a `ModuleConfig` (module sections only).
    pub fn to_module_config(&self) -> Option<ModuleConfig> {
        let payload_variant = match self {
            SectionValue::Mqtt(c) => module_config::PayloadVariant::Mqtt(c.clone()),
            SectionValue::Serial(c) => module_config::PayloadVariant::Serial(*c),
            SectionValue::Telemetry(c) => module_config::PayloadVariant::Telemetry(*c),
            SectionValue::CannedMessage(c) => {
                module_config::PayloadVariant::CannedMessage(c.clone())
            }
            SectionValue::ExternalNotification(c) => {
                module_config::PayloadVariant::ExternalNotification(*c)
            }
            SectionValue::StoreForward(c) => module_config::PayloadVariant::StoreForward(*c),
            SectionValue::RangeTest(c) => module_config::PayloadVariant::RangeTest(*c),
            _ => return None,
        };
        Some(ModuleConfig {
            payload_variant: Some(payload_variant),
        })
    }

    pub fn read(&self, key: &str) -> String {
        match self {
            SectionValue::Device(c) => read_device(c, key),
            SectionValue::Position(c) => read_position(c, key),
            SectionValue::Power(c) => read_power(c, key),
            SectionValue::Network(c) => read_network(c, key),
            SectionValue::Display(c) => read_display(c, key),
            SectionValue::Lora(c) => read_lora(c, key),
            SectionValue::Bluetooth(c) => read_bluetooth(c, key),
            SectionValue::Security(c) => read_security(c, key),
            SectionValue::Mqtt(c) => read_mqtt(c, key),
            SectionValue::Serial(c) => read_serial(c, key),
            SectionValue::Telemetry(c) => read_telemetry(c, key),
            SectionValue::CannedMessage(c) => read_canned(c, key),
            SectionValue::ExternalNotification(c) => read_extnotif(c, key),
            SectionValue::StoreForward(c) => read_storeforward(c, key),
            SectionValue::RangeTest(c) => read_rangetest(c, key),
        }
    }

    pub fn write(&mut self, key: &str, value: &str) -> Result<(), String> {
        match self {
            SectionValue::Device(c) => write_device(c, key, value),
            SectionValue::Position(c) => write_position(c, key, value),
            SectionValue::Power(c) => write_power(c, key, value),
            SectionValue::Network(c) => write_network(c, key, value),
            SectionValue::Display(c) => write_display(c, key, value),
            SectionValue::Lora(c) => write_lora(c, key, value),
            SectionValue::Bluetooth(c) => write_bluetooth(c, key, value),
            SectionValue::Security(c) => write_security(c, key, value),
            SectionValue::Mqtt(c) => write_mqtt(c, key, value),
            SectionValue::Serial(c) => write_serial(c, key, value),
            SectionValue::Telemetry(c) => write_telemetry(c, key, value),
            SectionValue::CannedMessage(c) => write_canned(c, key, value),
            SectionValue::ExternalNotification(c) => write_extnotif(c, key, value),
            SectionValue::StoreForward(c) => write_storeforward(c, key, value),
            SectionValue::RangeTest(c) => write_rangetest(c, key, value),
        }
    }
}

// Section specs

static LORA_FIELDS: &[Field] = &[
    enumerate(
        "region",
        "Region",
        "Regulatory region; must match your location.",
        REGIONS,
    ),
    boolean(
        "use_preset",
        "Use modem preset",
        "Use a preset instead of manual radio settings.",
    ),
    enumerate(
        "modem_preset",
        "Modem preset",
        "Speed/reliability trade-off.",
        MODEM_PRESETS,
    ),
    u32f(
        "hop_limit",
        "Hop limit",
        "Maximum number of mesh hops (1-7).",
        1,
        7,
    ),
    boolean(
        "tx_enabled",
        "Transmit enabled",
        "Turn the radio off for a receive-only node.",
    ),
    i32f(
        "tx_power",
        "TX power (dBm)",
        "Transmit power; 0 uses the board default.",
        0,
        30,
    ),
    u32f(
        "channel_num",
        "Channel number",
        "Frequency slot; leave at 0 for automatic.",
        0,
        255,
    ),
    f32f(
        "frequency_offset",
        "Frequency offset",
        "Manual frequency correction in MHz.",
    ),
    boolean(
        "override_duty_cycle",
        "Override duty cycle",
        "Allow exceeding the region duty cycle.",
    ),
    boolean(
        "ignore_mqtt",
        "Ignore MQTT",
        "Do not accept packets from the MQTT gateway.",
    ),
    boolean(
        "config_ok_to_mqtt",
        "Uplink to MQTT",
        "Allow this node's packets onto MQTT.",
    ),
];

static DEVICE_FIELDS: &[Field] = &[
    enumerate("role", "Role", "How this node behaves on the mesh.", ROLES),
    enumerate(
        "rebroadcast_mode",
        "Rebroadcast",
        "Which packets this node repeats.",
        REBROADCAST_MODES,
    ),
    u32f(
        "node_info_broadcast_secs",
        "Node info interval",
        "Seconds between node info broadcasts.",
        0,
        86_400,
    ),
    boolean(
        "disable_triple_click",
        "Disable triple click",
        "Disable the triple-click GPS toggle.",
    ),
    boolean(
        "led_heartbeat_disabled",
        "Disable LED heartbeat",
        "Turn off the periodic status LED.",
    ),
    text(
        "tzdef",
        "Time zone",
        "POSIX TZ string (e.g. UTC0, EST5EDT).",
    ),
];

static POSITION_FIELDS: &[Field] = &[
    u32f(
        "position_broadcast_secs",
        "Broadcast interval",
        "Seconds between position broadcasts.",
        0,
        86_400,
    ),
    boolean(
        "position_broadcast_smart_enabled",
        "Smart broadcast",
        "Only broadcast when moving.",
    ),
    boolean(
        "fixed_position",
        "Fixed position",
        "Report a fixed position instead of GPS.",
    ),
    enumerate("gps_mode", "GPS mode", "Hardware GPS behaviour.", GPS_MODES),
    u32f(
        "gps_update_interval",
        "GPS update interval",
        "Seconds between GPS reads.",
        0,
        86_400,
    ),
    u32f(
        "broadcast_smart_minimum_distance",
        "Smart minimum distance",
        "Minimum metres moved to update.",
        0,
        10_000,
    ),
];

static POWER_FIELDS: &[Field] = &[
    boolean(
        "is_power_saving",
        "Power saving",
        "Reduce power draw between transmissions.",
    ),
    u32f(
        "on_battery_shutdown_after_secs",
        "Shutdown on battery",
        "Seconds before shutdown on battery (0 = never).",
        0,
        86_400,
    ),
    u32f(
        "wait_bluetooth_secs",
        "Bluetooth wait",
        "Seconds to keep Bluetooth alive.",
        0,
        3_600,
    ),
    u32f(
        "sds_secs",
        "Screen delay",
        "Screen saver delay in seconds.",
        0,
        3_600,
    ),
    u32f(
        "ls_secs",
        "Light sleep",
        "Light-sleep duration in seconds.",
        0,
        3_600,
    ),
    u32f(
        "min_wake_secs",
        "Minimum wake",
        "Minimum awake time in seconds.",
        0,
        3_600,
    ),
];

static NETWORK_FIELDS: &[Field] = &[
    boolean("wifi_enabled", "WiFi enabled", "Enable the WiFi radio."),
    text(
        "wifi_ssid",
        "WiFi SSID",
        "Network name for the first WiFi network.",
    ),
    text(
        "wifi_psk",
        "WiFi password",
        "Leave empty for an open network.",
    ),
    boolean(
        "eth_enabled",
        "Ethernet enabled",
        "Enable Ethernet where supported.",
    ),
    text(
        "ntp_server",
        "NTP server",
        "Override the default NTP server.",
    ),
    enumerate(
        "address_mode",
        "Address mode",
        "DHCP or a static address.",
        ADDRESS_MODES,
    ),
];

static DISPLAY_FIELDS: &[Field] = &[
    u32f(
        "screen_on_secs",
        "Screen on time",
        "Seconds before the screen sleeps.",
        0,
        3_600,
    ),
    u32f(
        "auto_screen_carousel_secs",
        "Carousel interval",
        "Seconds between auto-scrolled screens.",
        0,
        3_600,
    ),
    enumerate(
        "displaymode",
        "Display mode",
        "Panel colour mode.",
        DISPLAY_MODES,
    ),
    enumerate("units", "Units", "Displayed measurement units.", UNITS),
    enumerate(
        "gps_format",
        "GPS format",
        "Coordinate display format.",
        GPS_FORMATS,
    ),
    enumerate(
        "oled",
        "OLED type",
        "Panel controller; Auto usually works.",
        OLED_TYPES,
    ),
    boolean("flip_screen", "Flip screen", "Rotate the display 180°."),
    boolean(
        "compass_north_top",
        "North up",
        "Orient the compass with north at the top.",
    ),
];

static BLUETOOTH_FIELDS: &[Field] = &[
    boolean(
        "enabled",
        "Bluetooth enabled",
        "Enable the Bluetooth radio.",
    ),
    enumerate(
        "mode",
        "Pairing mode",
        "How BLE pairing is authorised.",
        PAIRING_MODES,
    ),
    u32f(
        "fixed_pin",
        "Fixed PIN",
        "PIN used when pairing mode is Fixed (0-999999).",
        0,
        999_999,
    ),
];

static SECURITY_FIELDS: &[Field] = &[
    boolean(
        "is_managed",
        "Managed device",
        "This node is managed by another device.",
    ),
    boolean(
        "serial_enabled",
        "Serial console",
        "Enable the serial console.",
    ),
    boolean(
        "debug_log_api_enabled",
        "Debug log API",
        "Expose device logs over the protocol.",
    ),
    boolean(
        "admin_channel_enabled",
        "Admin channel",
        "Allow admin commands from the mesh.",
    ),
];

static MQTT_FIELDS: &[Field] = &[
    boolean("enabled", "MQTT enabled", "Connect to an MQTT broker."),
    text(
        "address",
        "Broker address",
        "Hostname or IP of the MQTT broker.",
    ),
    text("username", "Username", "Broker username."),
    password("password", "Password", "Broker password."),
    boolean("encryption_enabled", "Encryption", "Encrypt MQTT traffic."),
    boolean("json_enabled", "JSON", "Publish JSON as well as protobufs."),
    boolean("tls_enabled", "TLS", "Use TLS for the broker connection."),
    text("root", "Root topic", "MQTT root topic (default msh)."),
    boolean(
        "proxy_to_client_enabled",
        "Proxy to client",
        "Relay MQTT through a client connection.",
    ),
    boolean(
        "map_reporting_enabled",
        "Map reporting",
        "Report position to a map server.",
    ),
];

static SERIAL_FIELDS: &[Field] = &[
    boolean("enabled", "Serial enabled", "Enable the serial module."),
    boolean(
        "echo",
        "Echo",
        "Echo received data back to the serial port.",
    ),
    u32f("rxd", "RX pin", "Receive pin (0 = default).", 0, 255),
    u32f("txd", "TX pin", "Transmit pin (0 = default).", 0, 255),
    i32f("baud", "Baud rate", "Serial baud rate.", 0, 9_999_999),
    u32f(
        "timeout",
        "Timeout",
        "Message timeout in milliseconds.",
        0,
        86_400_000,
    ),
    enumerate("mode", "Mode", "How the serial port is used.", SERIAL_MODES),
    boolean(
        "override_console_serial_port",
        "Override console port",
        "Reuse the console serial port.",
    ),
];

static TELEMETRY_FIELDS: &[Field] = &[
    u32f(
        "device_update_interval",
        "Device interval",
        "Seconds between device metric broadcasts.",
        0,
        86_400,
    ),
    u32f(
        "environment_update_interval",
        "Environment interval",
        "Seconds between environment broadcasts.",
        0,
        86_400,
    ),
    boolean(
        "environment_measurement_enabled",
        "Environment metrics",
        "Collect environment sensors.",
    ),
    boolean(
        "environment_screen_enabled",
        "Environment on screen",
        "Show environment metrics on screen.",
    ),
    boolean(
        "environment_display_fahrenheit",
        "Fahrenheit",
        "Display temperature in °F.",
    ),
    boolean(
        "air_quality_enabled",
        "Air quality",
        "Collect air-quality metrics.",
    ),
    u32f(
        "air_quality_interval",
        "Air quality interval",
        "Seconds between air-quality readings.",
        0,
        86_400,
    ),
    boolean(
        "power_measurement_enabled",
        "Power metrics",
        "Collect power metrics.",
    ),
    u32f(
        "power_update_interval",
        "Power interval",
        "Seconds between power broadcasts.",
        0,
        86_400,
    ),
    boolean(
        "health_measurement_enabled",
        "Health metrics",
        "Collect health metrics.",
    ),
    u32f(
        "health_update_interval",
        "Health interval",
        "Seconds between health broadcasts.",
        0,
        86_400,
    ),
];

static CANNED_FIELDS: &[Field] = &[
    boolean(
        "enabled",
        "Canned messages enabled",
        "Enable the canned message module.",
    ),
    text(
        "allow_input_source",
        "Input source",
        "Allowed input source (e.g. rotary, keyboard).",
    ),
    boolean("send_bell", "Send bell", "Ring a bell on delivery."),
];

static EXTNOTIF_FIELDS: &[Field] = &[
    boolean(
        "enabled",
        "Notifications enabled",
        "Enable external notifications.",
    ),
    u32f(
        "output_ms",
        "Output duration",
        "Buzzer/vibration duration in ms.",
        0,
        60_000,
    ),
    boolean(
        "active",
        "Active high",
        "Output is active-high rather than active-low.",
    ),
    boolean(
        "alert_message",
        "Alert on message",
        "Notify on incoming messages.",
    ),
    boolean(
        "alert_bell",
        "Alert on bell",
        "Notify on the bell character.",
    ),
    boolean("use_pwm", "Use PWM", "Drive the buzzer with PWM."),
    u32f(
        "nag_timeout",
        "Nag timeout",
        "Seconds to keep nagging (0 = once).",
        0,
        3_600,
    ),
];

static STOREFORWARD_FIELDS: &[Field] = &[
    boolean(
        "enabled",
        "Store & forward enabled",
        "Enable the store & forward module.",
    ),
    boolean("heartbeat", "Heartbeat", "Broadcast a heartbeat."),
    u32f(
        "records",
        "Records",
        "Number of messages to keep.",
        0,
        10_000,
    ),
    u32f(
        "history_return_max",
        "History max",
        "Maximum messages returned on request.",
        0,
        10_000,
    ),
    u32f(
        "history_return_window",
        "History window",
        "Seconds of history available.",
        0,
        86_400,
    ),
    boolean("is_server", "Server", "Act as the store & forward server."),
];

static RANGETEST_FIELDS: &[Field] = &[
    boolean(
        "enabled",
        "Range test enabled",
        "Enable the range test module.",
    ),
    u32f(
        "sender",
        "Sender interval",
        "Seconds between test transmissions (0 = receiver).",
        0,
        86_400,
    ),
    boolean(
        "save",
        "Save to file",
        "Save received test packets to the filesystem.",
    ),
];

static LORA_SPEC: SectionSpec = SectionSpec {
    section: Section::Lora,
    title: "LoRa",
    description: "Radio region, preset and transmit settings.",
    fields: LORA_FIELDS,
};
static DEVICE_SPEC: SectionSpec = SectionSpec {
    section: Section::Device,
    title: "Device",
    description: "Node role, rebroadcast behaviour and identity.",
    fields: DEVICE_FIELDS,
};
static POSITION_SPEC: SectionSpec = SectionSpec {
    section: Section::Position,
    title: "Position",
    description: "GPS and position broadcast settings.",
    fields: POSITION_FIELDS,
};
static POWER_SPEC: SectionSpec = SectionSpec {
    section: Section::Power,
    title: "Power",
    description: "Power saving and battery behaviour.",
    fields: POWER_FIELDS,
};
static NETWORK_SPEC: SectionSpec = SectionSpec {
    section: Section::Network,
    title: "Network",
    description: "WiFi, Ethernet and NTP settings.",
    fields: NETWORK_FIELDS,
};
static DISPLAY_SPEC: SectionSpec = SectionSpec {
    section: Section::Display,
    title: "Display",
    description: "Screen, units and orientation.",
    fields: DISPLAY_FIELDS,
};
static BLUETOOTH_SPEC: SectionSpec = SectionSpec {
    section: Section::Bluetooth,
    title: "Bluetooth",
    description: "Bluetooth radio and pairing.",
    fields: BLUETOOTH_FIELDS,
};
static SECURITY_SPEC: SectionSpec = SectionSpec {
    section: Section::Security,
    title: "Security",
    description: "Console, admin channel and managed mode.",
    fields: SECURITY_FIELDS,
};
static MQTT_SPEC: SectionSpec = SectionSpec {
    section: Section::Mqtt,
    title: "MQTT",
    description: "Broker connection and gateway behaviour.",
    fields: MQTT_FIELDS,
};
static SERIAL_SPEC: SectionSpec = SectionSpec {
    section: Section::Serial,
    title: "Serial",
    description: "Serial module pins, baud and mode.",
    fields: SERIAL_FIELDS,
};
static TELEMETRY_SPEC: SectionSpec = SectionSpec {
    section: Section::Telemetry,
    title: "Telemetry",
    description: "Metric collection and broadcast intervals.",
    fields: TELEMETRY_FIELDS,
};
static CANNED_SPEC: SectionSpec = SectionSpec {
    section: Section::CannedMessage,
    title: "Canned messages",
    description: "Predefined messages and input source.",
    fields: CANNED_FIELDS,
};
static EXTNOTIF_SPEC: SectionSpec = SectionSpec {
    section: Section::ExternalNotification,
    title: "External notification",
    description: "Buzzers, LEDs and vibration alerts.",
    fields: EXTNOTIF_FIELDS,
};
static STOREFORWARD_SPEC: SectionSpec = SectionSpec {
    section: Section::StoreForward,
    title: "Store & forward",
    description: "Store messages for nodes that are offline.",
    fields: STOREFORWARD_FIELDS,
};
static RANGETEST_SPEC: SectionSpec = SectionSpec {
    section: Section::RangeTest,
    title: "Range test",
    description: "Transmit periodic test packets.",
    fields: RANGETEST_FIELDS,
};

static ALL_SPECS: &[&SectionSpec] = &[
    &LORA_SPEC,
    &DEVICE_SPEC,
    &POSITION_SPEC,
    &POWER_SPEC,
    &NETWORK_SPEC,
    &DISPLAY_SPEC,
    &BLUETOOTH_SPEC,
    &SECURITY_SPEC,
    &MQTT_SPEC,
    &SERIAL_SPEC,
    &TELEMETRY_SPEC,
    &CANNED_SPEC,
    &EXTNOTIF_SPEC,
    &STOREFORWARD_SPEC,
    &RANGETEST_SPEC,
];

/// Every section, in the order they appear in Settings.
pub fn all_specs() -> &'static [&'static SectionSpec] {
    ALL_SPECS
}

pub fn spec(section: Section) -> &'static SectionSpec {
    all_specs()
        .iter()
        .find(|s| s.section == section)
        .expect("every Section has a spec")
}

// Editors

/// An open config-section editor.
#[derive(Debug, Clone)]
pub struct Editor {
    pub spec: &'static SectionSpec,
    pub original: SectionValue,
    pub values: HashMap<String, String>,
    pub error: Option<String>,
}

impl Editor {
    pub fn new(section: Section, current: Option<SectionValue>) -> Self {
        let spec = spec(section);
        let original = current.unwrap_or_else(|| SectionValue::default_for(section));
        let values = spec
            .fields
            .iter()
            .map(|field| (field.key.to_string(), original.read(field.key)))
            .collect();
        Self {
            spec,
            original,
            values,
            error: None,
        }
    }

    pub fn value(&self, key: &str) -> &str {
        self.values.get(key).map(String::as_str).unwrap_or("")
    }

    pub fn set(&mut self, key: &str, value: String) {
        self.values.insert(key.to_string(), value);
        self.error = None;
    }

    /// Apply the edited values to a fresh copy of the original config,
    /// validating numeric ranges on the way.
    pub fn build(&self) -> Result<SectionValue, String> {
        let mut value = self.original.clone();
        for field in self.spec.fields {
            let raw = self.value(field.key);
            match field.kind {
                FieldKind::U32 { min, max } => {
                    let parsed: u32 = raw
                        .trim()
                        .parse()
                        .map_err(|_| format!("{} must be a whole number", field.label))?;
                    if parsed < min || parsed > max {
                        return Err(format!("{} must be between {min} and {max}", field.label));
                    }
                }
                FieldKind::I32 { min, max } => {
                    let parsed: i32 = raw
                        .trim()
                        .parse()
                        .map_err(|_| format!("{} must be a whole number", field.label))?;
                    if parsed < min || parsed > max {
                        return Err(format!("{} must be between {min} and {max}", field.label));
                    }
                }
                _ => {}
            }
            value.write(field.key, raw)?;
        }
        Ok(value)
    }
}

/// An open channel editor.
#[derive(Debug, Clone)]
pub struct ChannelEditor {
    pub index: i32,
    pub original: Channel,
    pub values: HashMap<String, String>,
    pub error: Option<String>,
}

impl ChannelEditor {
    pub fn new(index: i32, original: Channel) -> Self {
        let settings = original.settings.clone().unwrap_or_default();
        let mut values = HashMap::new();
        values.insert("name".to_string(), settings.name.clone());
        values.insert("psk".to_string(), bytes_to_hex(&settings.psk));
        values.insert("role".to_string(), original.role.to_string());
        values.insert(
            "uplink_enabled".to_string(),
            settings.uplink_enabled.to_string(),
        );
        values.insert(
            "downlink_enabled".to_string(),
            settings.downlink_enabled.to_string(),
        );
        Self {
            index,
            original,
            values,
            error: None,
        }
    }

    pub fn value(&self, key: &str) -> &str {
        self.values.get(key).map(String::as_str).unwrap_or("")
    }

    pub fn set(&mut self, key: &str, value: String) {
        self.values.insert(key.to_string(), value);
        self.error = None;
    }

    pub fn build(&self) -> Result<Channel, String> {
        let mut channel = self.original.clone();
        let settings = channel
            .settings
            .get_or_insert_with(ChannelSettings::default);
        settings.name = self.value("name").to_string();
        settings.psk = hex_to_bytes(self.value("psk"))?;
        settings.uplink_enabled = self.value("uplink_enabled").eq_ignore_ascii_case("true");
        settings.downlink_enabled = self.value("downlink_enabled").eq_ignore_ascii_case("true");
        // Channel 0 is always primary; others may be disabled/secondary.
        channel.role = if self.index == 0 {
            meshtastic_protobufs::meshtastic::channel::Role::Primary as i32
        } else {
            self.value("role").trim().parse().unwrap_or(channel.role)
        };
        Ok(channel)
    }
}

/// Render a byte slice as lowercase hex.
pub fn bytes_to_hex(bytes: &[u8]) -> String {
    let mut out = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        out.push_str(&format!("{byte:02x}"));
    }
    out
}

/// Parse a hex string (even length) into bytes.
pub fn hex_to_bytes(text: &str) -> Result<Vec<u8>, String> {
    let text = text.trim();
    if text.is_empty() {
        return Ok(Vec::new());
    }
    if text.len() % 2 != 0 {
        return Err("hex value must have an even number of digits".to_string());
    }
    (0..text.len())
        .step_by(2)
        .map(|i| {
            u8::from_str_radix(&text[i..i + 2], 16)
                .map_err(|_| format!("invalid hex: {}", &text[i..i + 2]))
        })
        .collect()
}

/// Generate a random 256-bit channel key as hex.
pub fn random_channel_key() -> String {
    let key: [u8; 32] = rand::random();
    bytes_to_hex(&key)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lora_round_trips_through_editor() {
        let mut lora = LoRaConfig {
            region: 1,
            hop_limit: 3,
            ..Default::default()
        };
        lora.tx_power = 27;
        let value = SectionValue::Lora(lora);
        let mut editor = Editor::new(Section::Lora, Some(value));
        assert_eq!(editor.value("region"), "1");
        editor.set("region", "3".into());
        editor.set("hop_limit", "5".into());
        editor.set("tx_enabled", "true".into());
        let built = editor.build().unwrap();
        let config = built.to_config().unwrap();
        match config.payload_variant {
            Some(config::PayloadVariant::Lora(l)) => {
                assert_eq!(l.region, 3);
                assert_eq!(l.hop_limit, 5);
                assert!(l.tx_enabled);
            }
            _ => panic!("expected lora"),
        }
    }

    #[test]
    fn from_config_extracts_and_fills_editor() {
        let config = Config {
            payload_variant: Some(config::PayloadVariant::Lora(LoRaConfig {
                region: 3,
                hop_limit: 5,
                tx_power: 20,
                ..Default::default()
            })),
        };
        let value = SectionValue::from_config(Section::Lora, &config).unwrap();
        let editor = Editor::new(Section::Lora, Some(value));
        assert_eq!(editor.value("region"), "3");
        assert_eq!(editor.value("hop_limit"), "5");
        assert_eq!(editor.value("tx_power"), "20");
        assert_eq!(editor.value("tx_enabled"), "false");

        // Module sections come from ModuleConfig.
        let module = ModuleConfig {
            payload_variant: Some(module_config::PayloadVariant::Telemetry(TelemetryConfig {
                device_update_interval: 900,
                ..Default::default()
            })),
        };
        let value = SectionValue::from_module_config(Section::Telemetry, &module).unwrap();
        let editor = Editor::new(Section::Telemetry, Some(value));
        assert_eq!(editor.value("device_update_interval"), "900");
        assert!(SectionValue::from_config(Section::Telemetry, &config).is_none());
    }

    #[test]
    fn invalid_number_is_reported() {
        let editor = Editor::new(Section::Lora, None);
        let mut editor = editor;
        editor.set("hop_limit", "not-a-number".into());
        assert!(editor.build().is_err());
    }

    #[test]
    fn module_config_wrapping() {
        let value = SectionValue::Mqtt(MqttConfig {
            enabled: true,
            address: "mqtt.local".into(),
            ..Default::default()
        });
        let module = value.to_module_config().unwrap();
        assert!(matches!(
            module.payload_variant,
            Some(module_config::PayloadVariant::Mqtt(_))
        ));
        assert!(value.to_config().is_none());
    }

    #[test]
    fn channel_editor_builds_psk() {
        let channel = Channel {
            index: 2,
            role: 2,
            settings: Some(ChannelSettings {
                name: "Team".into(),
                psk: vec![0xab, 0xcd],
                ..Default::default()
            }),
        };
        let mut editor = ChannelEditor::new(2, channel);
        assert_eq!(editor.value("psk"), "abcd");
        editor.set("psk", "0102".into());
        editor.set("name", "Renamed".into());
        let built = editor.build().unwrap();
        assert_eq!(built.settings.unwrap().psk, vec![0x01, 0x02]);
        assert_eq!(built.role, 2);
    }

    #[test]
    fn hex_helpers() {
        assert_eq!(bytes_to_hex(&[0x00, 0xff, 0x10]), "00ff10");
        assert_eq!(hex_to_bytes("00ff10").unwrap(), vec![0x00, 0xff, 0x10]);
        assert!(hex_to_bytes("abc").is_err());
        assert!(hex_to_bytes("zz").is_err());
    }
}
